"""Only the committed synthetic fixture may execute, only against ephemeral loopback.
The product CLI is never given an execution feature. This harness is not a user-input runner.
"""
from pathlib import Path
from urllib.parse import urlsplit
import copy, hashlib, json, os, queue, socketserver, subprocess, tempfile, threading

ROOT = Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / 'evidence'
CLI = ROOT / 'target/debug/request-slip'
HURL = ROOT / '.native/bin/hurl'
FMT = ROOT / '.native/bin/hurlfmt'
FIXTURE = ROOT / 'fixtures/static.hurl'
FIXTURE_SHA = '41c9643200c3567f40507ad2531cd8c90a0058d33a69aca3c0dd338e38fb9bad'
FIXED = FIXTURE.read_bytes()
assert hashlib.sha256(FIXED).hexdigest() == FIXTURE_SHA
SELECTED = [1, 2, 3, 4, 5, 6, 7]
SELECTED_HEADER_NAMES = {'x-dup', 'x-empty', 'x-literal', 'x-case', 'content-type', 'user-agent'}

# Independent literal expectations: these are not generated by the exporter or Hurl.
EXPECTED = [
    {'method': 'GET', 'target': '/search?keep=a%2Bb&empty=&tag=red%20blue&tag=a%2Bb&word=%E6%97%A5%E6%9C%AC%E8%AA%9E', 'headers': [['x-dup','first'],['x-dup','second'],['x-empty',''],['x-literal',"apostrophe's $(printf STAYS_LITERAL) `printf ALSO_LITERAL`"],['user-agent','hurl/8.0.1']], 'body': ''},
    {'method': 'POST', 'target': '/form', 'headers': [['x-case','form'],['content-type','application/x-www-form-urlencoded'],['user-agent','hurl/8.0.1']], 'body': 'item=one%20two&item=%3D%26%40&word=%E6%97%A5%E6%9C%AC%E8%AA%9E'},
    {'method': 'POST', 'target': '/raw', 'headers': [['x-case','raw'],['user-agent','hurl/8.0.1']], 'body': "@first's 日本語\nliteral \\n and {{raw}} $(printf RAW_LITERAL) `printf STILL_LITERAL`\n"},
    {'method': 'POST', 'target': '/text', 'headers': [['x-case','text'],['user-agent','hurl/8.0.1']], 'body': "one\\n is literal; next is a real line\ntwo's 日本語\n"},
    {'method': 'POST', 'target': '/oneline', 'headers': [['x-case','oneline'],['user-agent','hurl/8.0.1']], 'body': "one\nescaped's 日本語 {{literal}}"},
    {'method': 'POST', 'target': '/empty', 'headers': [['x-case','empty'],['user-agent','hurl/8.0.1']], 'body': ''},
    {'method': 'GET', 'target': '/question?word=a%20b', 'headers': [['x-case','question'],['user-agent','hurl/8.0.1']], 'body': ''},
    {'method': 'GET', 'target': '/UNSELECTED_SENTINEL', 'headers': [['x-case','omitted'],['user-agent','hurl/8.0.1']], 'body': ''},
]

captured = queue.Queue()
class Capture(socketserver.BaseRequestHandler):
    def handle(self):
        self.request.settimeout(5)
        data = b''
        while b'\r\n\r\n' not in data:
            chunk = self.request.recv(4096)
            if not chunk: raise AssertionError('Incomplete request headers')
            data += chunk
            assert len(data) <= 65536
        head, body = data.split(b'\r\n\r\n',1)
        lines = head.split(b'\r\n')
        method, target, version = lines[0].split(b' ')
        assert version in [b'HTTP/1.0', b'HTTP/1.1']
        pairs = [line.split(b':',1) for line in lines[1:]]
        headers = [(k.decode('ascii').lower(),v.strip(b' \t').decode('utf-8')) for k,v in pairs]
        assert not any(k in ['authorization','proxy-authorization','cookie','transfer-encoding'] for k,v in headers)
        sizes = [v for k,v in headers if k == 'content-length']
        assert len(sizes) <= 1
        length = int(sizes[0]) if sizes else 0
        assert 0 <= length <= 65536
        while len(body) < length:
            chunk = self.request.recv(length-len(body))
            if not chunk: raise AssertionError('Incomplete body')
            body += chunk
        assert len(body) == length
        record = {'method': method.decode('ascii'), 'target': target.decode('ascii'), 'headers': [[k,v] for k,v in headers if k in SELECTED_HEADER_NAMES], 'body': body.decode('utf-8')}
        captured.put(record)
        self.request.sendall(b'HTTP/1.1 200 OK\r\nContent-Length: 0\r\nConnection: close\r\n\r\n')

def compare(actual, expected):
    assert actual == expected, json.dumps({'expected': expected, 'actual': actual}, ensure_ascii=False)

def check_argv(argv, port):
    assert argv[:2] == ['curl','--disable'] and all(isinstance(x,str) and '\0' not in x for x in argv)
    switches = {'--disable','--globoff','--path-as-is'}
    values = {'--proto','--request','--url','--header','--data-raw'}
    seen = {}
    i = 1
    while i < len(argv):
        key = argv[i];seen[key] = seen.get(key,0)+1
        if key in switches: i += 1;continue
        assert key in values and i+1 < len(argv)
        value = argv[i+1]
        if key == '--proto': assert value == '=http,https'
        if key == '--request': assert value in ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
        if key == '--url':
            url = urlsplit(value)
            assert url.scheme == 'http' and url.hostname == '127.0.0.1' and url.port == port and not url.username and not url.password and not url.fragment
        if key == '--header': assert not value.startswith('@') and '\r' not in value and '\n' not in value
        i += 2
    for name in ['--disable','--globoff','--path-as-is','--proto','--request','--url']: assert seen.get(name) == 1
    assert seen.get('--data-raw',0) <= 1
    assert sum(len(x.encode()) for x in argv) < 131072

with tempfile.TemporaryDirectory(prefix='request-slip-gate-') as temp:
    folder = Path(temp)
    environment = {'PATH': os.environ['PATH'], 'HOME': temp, 'CURL_HOME': temp, 'NO_PROXY': '*', 'no_proxy': '*', 'LANG': 'C.UTF-8'}
    server = socketserver.TCPServer(('127.0.0.1',0),Capture)
    thread = threading.Thread(target=server.serve_forever,daemon=True);thread.start()
    try:
        port = server.server_address[1]
        base = f'http://127.0.0.1:{port}'
        source = FIXED.decode().replace('http://fixture.invalid',base)
        assert source.count(base) == 8 and '.invalid' not in source
        fixture_path = folder/'fixture.hurl';fixture_path.write_text(source)

        def cli(*extra, input_bytes=None, ok=True):
            p=subprocess.run([str(CLI),str(fixture_path) if input_bytes is None else '-',*extra],input=input_bytes,env=environment,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10)
            assert (p.returncode == 0) == ok, p.stderr.decode(errors='replace')
            if not ok: assert not p.stdout
            return p

        # Artifacts are actual CLI stdout bytes, then consumed from disk below.
        selector=','.join(map(str,SELECTED))
        (EVIDENCE/'selected.argv.json').write_bytes(cli('--select',selector,'--format','json').stdout)
        (EVIDENCE/'selected.curl.txt').write_bytes(cli('--select',selector,'--format','text').stdout)
        receipt=json.loads((EVIDENCE/'selected.argv.json').read_text())
        assert receipt['selected_entries'] == SELECTED and receipt['source_entry_count'] == 8
        assert [r['source_line'] for r in receipt['requests']] == [2,13,21,29,37,42,47]
        assert receipt['source_sha256'] == hashlib.sha256(source.encode()).hexdigest()
        assert 'UNSELECTED_SENTINEL' not in (EVIDENCE/'selected.argv.json').read_text()
        assert 'UNSELECTED_SENTINEL' not in (EVIDENCE/'selected.curl.txt').read_text()
        assert cli('--select',selector,'--format','json').stdout == (EVIDENCE/'selected.argv.json').read_bytes()
        assert cli('--select',selector,'--format','json',input_bytes=source.encode()).stdout == (EVIDENCE/'selected.argv.json').read_bytes()
        actual_text=(EVIDENCE/'selected.curl.txt').read_text()
        text_header='# RequestSlip: POSIX cURL command text, not executed\n# Each request is independent; review before manually running.\n'
        assert actual_text.startswith(text_header)
        cursor=len(text_header);actual_commands=[]
        for item in receipt['requests']:
            framing=f"\n# Entry {item['entry']} (source line {item['source_line']})\n"
            assert actual_text[cursor:cursor+len(framing)]==framing
            cursor+=len(framing)
            command=actual_text[cursor:cursor+len(item['curl_text'])]
            assert command==item['curl_text']
            cursor+=len(command);assert actual_text[cursor:cursor+1]=='\n';cursor+=1
            actual_commands.append(command)
        assert cursor==len(actual_text)

        # Only this verified, fixed fixture may reach Hurl. No imported/user input is executed.
        hurl_run=subprocess.run([str(HURL),'--silent','--max-time','5',str(fixture_path)],env=environment,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=30)
        (EVIDENCE/'hurl-fixture.stderr.txt').write_bytes(hurl_run.stderr)
        assert hurl_run.returncode == 0, hurl_run.stderr.decode(errors='replace')
        original = [captured.get(timeout=5) for _ in range(8)]
        for actual,expected in zip(original,EXPECTED,strict=True): compare(actual,expected)

        def curl(argv):
            check_argv(argv,port)
            result=subprocess.run(['/usr/bin/curl',*argv[1:],'--proxy','','--noproxy','*','--connect-timeout','2','--max-time','5','--silent','--show-error'],env=environment,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10)
            assert result.returncode == 0, result.stderr.decode(errors='replace')
            return captured.get(timeout=5)

        converted=[]
        for item,actual_command in zip(receipt['requests'],actual_commands,strict=True):
            # Only canonical literal POSIX words are admitted to the synthetic shell test.
            canonical=' \\\n  '.join("'"+word.replace("'", "'\"'\"'")+"'" for word in item['argv'])
            assert actual_command==canonical
            check_argv(item['argv'],port)
            # Controlled synthetic shell literals only; set/printf capture argv, never invoke curl.
            shell="set -- "+actual_command+"\nprintf '%s\\0' \"$@\""
            words=subprocess.check_output(['/bin/sh','-c',shell],env=environment,timeout=5).split(b'\0')[:-1]
            assert words == [v.encode() for v in item['argv']]
            actual=curl(item['argv']); compare(actual,EXPECTED[item['entry']-1]);compare(actual,original[item['entry']-1]);converted.append(actual)

        subset=cli('--select','2','--format','json').stdout
        (EVIDENCE/'subset.argv.json').write_bytes(subset)
        subset=json.loads(subset);assert len(subset['requests'])==1 and subset['requests'][0]['entry']==2
        compare(curl(subset['requests'][0]['argv']),EXPECTED[1])

        mutations=[]
        for name,entry in [('method',0),('query-order',0),('duplicate-header',0),('body-byte',2)]:
            argv=copy.deepcopy(receipt['requests'][entry]['argv'])
            if name=='method': argv[argv.index('--request')+1]='PATCH'
            if name=='query-order':
                p=argv.index('--url')+1;argv[p]=argv[p].replace('tag=red%20blue&tag=a%2Bb','tag=a%2Bb&tag=red%20blue')
            if name=='duplicate-header':
                p=argv.index('X-Dup: second');del argv[p-1:p+1]
            if name=='body-byte': argv[argv.index('--data-raw')+1]+='!'
            actual=curl(argv)
            try: compare(actual,EXPECTED[entry])
            except AssertionError: mutations.append(name)
            else: raise AssertionError('The fixed oracle accepted a corrupted request')

        # hurlfmt-only JSON really omits BasicAuth; the official-AST product rejects it.
        auth=b'GET http://fixture.invalid/\n[BasicAuth]\nsynthetic-user: synthetic-password\n'
        plain=b'GET http://fixture.invalid/\n'
        encoded=[subprocess.check_output([str(FMT),'--out','json'],input=x,env=environment,timeout=10) for x in [plain,auth]]
        assert json.loads(encoded[0]) == json.loads(encoded[1])
        assert b'BasicAuth' in cli(input_bytes=auth,ok=False).stderr
        for bad in [b'GET http://fixture.invalid/\nX-A: \xff\n',b'GET http://fixture.invalid/\n\0',b'x'*262145]: cli(input_bytes=bad,ok=False)
        cli('--format','json','--format','json',ok=False)
        report={'status':'native-wire-parity-passed','source_fixture_sha256':FIXTURE_SHA,'original_hurl_requests':8,'selected_curl_requests':len(converted),'single_subset_requests':1,'negative_controls':mutations,'fixed_expected':EXPECTED,'original_hurl_capture':original,'actual_export_curl_capture':converted,'shell_argv_fidelity':True,'hurlfmt_basic_auth_omission_confirmed':True,'user_inputs_executed':0,'destinations':'Only disposable 127.0.0.1 listener; port is allocated by the OS','curl_version':subprocess.check_output(['/usr/bin/curl','--version'],text=True).splitlines()[0]}
        (EVIDENCE/'native-result.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
        print('Native wire parity: 8 original Hurl requests, 7 selected cURL exports, 1 subset, 4 corruption controls, POSIX argv fidelity, BasicAuth omission confirmed')
    finally:
        server.shutdown();server.server_close();thread.join(timeout=5)
